const CSV_URL=window.PRODUCT_CSV_URL;let products=[],entries=[],activeFilter="Alle",activeView="cash";
const fallbackProducts=[{aktiv:true,kategorie:"Getränke",produkt:"Bier",preis:3.5,icon:"🍺",reihenfolge:1},{aktiv:true,kategorie:"Getränke",produkt:"Weizenbier",preis:3.8,icon:"🍺",reihenfolge:2},{aktiv:true,kategorie:"Wein",produkt:"Riesling",preis:4.5,icon:"🍷",reihenfolge:10},{aktiv:true,kategorie:"Wein",produkt:"Schorle",preis:3.5,icon:"🍷",reihenfolge:11},{aktiv:true,kategorie:"Alkoholfrei",produkt:"Cola",preis:3,icon:"🥤",reihenfolge:20},{aktiv:true,kategorie:"Alkoholfrei",produkt:"Wasser",preis:2.5,icon:"💧",reihenfolge:21},{aktiv:true,kategorie:"Essen",produkt:"Bratwurst",preis:4.5,icon:"🌭",reihenfolge:30},{aktiv:true,kategorie:"Essen",produkt:"Steak",preis:8,icon:"🥩",reihenfolge:31},{aktiv:true,kategorie:"Essen",produkt:"Pommes",preis:3,icon:"🍟",reihenfolge:32},{aktiv:true,kategorie:"Pfand",produkt:"Pfand",preis:4,icon:"➕",reihenfolge:90},{aktiv:true,kategorie:"Pfand",produkt:"Pfand zurück",preis:-4,icon:"➖",reihenfolge:91}];
const el={total:document.getElementById("total"),status:document.getElementById("status"),filters:document.getElementById("filters"),productArea:document.getElementById("productArea"),cartPanel:document.getElementById("cartPanel"),cartList:document.getElementById("cartList"),refreshBtn:document.getElementById("refreshBtn"),undoBtn:document.getElementById("undoBtn"),resetBtn:document.getElementById("resetBtn"),cashTab:document.getElementById("cashTab"),listTab:document.getElementById("listTab")};
function euro(v){return v.toLocaleString("de-DE",{style:"currency",currency:"EUR"})}
function parseCSV(t){const rows=[];let row=[],cell="",q=false;for(let i=0;i<t.length;i++){const c=t[i],n=t[i+1];if(c=='"'&&q&&n=='"'){cell+='"';i++}else if(c=='"')q=!q;else if(c==","&&!q){row.push(cell);cell=""}else if((c=="\n"||c=="\r")&&!q){if(c=="\r"&&n=="\n")i++;row.push(cell);cell="";if(row.some(v=>v.trim()!=""))rows.push(row);row=[]}else cell+=c}row.push(cell);if(row.some(v=>v.trim()!=""))rows.push(row);return rows}
function norm(h){return String(h).trim().toLowerCase().replaceAll(" ","")}
function price(v){return Number(String(v??"").replace("€","").replaceAll(".","").replace(",",".").trim())||0}
function rowsToProducts(rows){if(!rows.length)return[];const h=rows[0].map(norm),idx=n=>h.indexOf(norm(n));return rows.slice(1).map(r=>{const get=n=>r[idx(n)]??"",a=String(get("Aktiv")).trim().toLowerCase();return{aktiv:!["false","nein","0","no"].includes(a),kategorie:get("Kategorie")||"Produkte",produkt:get("Produkt")||"Ohne Name",preis:price(get("Preis")),icon:get("Icon")||"⬜",reihenfolge:Number(get("Reihenfolge"))||999}}).filter(p=>p.aktiv).sort((a,b)=>a.reihenfolge-b.reihenfolge)}
async function loadProducts(force=false){el.status.textContent=force?"Produkte werden aktualisiert …":"Produkte werden geladen …";try{const res=await fetch(CSV_URL+(CSV_URL.includes("?")?"&":"?")+"t="+Date.now(),{cache:"no-store"});if(!res.ok)throw Error();const text=await res.text();products=rowsToProducts(parseCSV(text));if(!products.length)throw Error();localStorage.setItem("dhc_products",JSON.stringify(products));el.status.textContent=`${entries.length} Positionen · Produkte aktuell`}catch(e){const saved=localStorage.getItem("dhc_products");products=saved?JSON.parse(saved):fallbackProducts;el.status.textContent=saved?`${entries.length} Positionen · Offline-Daten`:`${entries.length} Positionen · Beispieldaten`}render()}
function slug(c){return"category-"+String(c).toLowerCase().replace("ä","ae").replace("ö","oe").replace("ü","ue").replace("ß","ss").replace(/[^a-z0-9]+/g,"-")}
function catIcon(c){const s=String(c).toLowerCase();if(s==="alle")return"▦";if(s.includes("geträn")||s.includes("getraen"))return"🥤";if(s.includes("wein"))return"🍷";if(s.includes("essen"))return"🍴";if(s.includes("pfand"))return"◎";return"•"}
function esc(s){return String(s).replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[m]))}
function renderFilters(){const cats=["Alle",...Array.from(new Set(products.map(p=>p.kategorie)))];el.filters.innerHTML=cats.map(c=>`<button class="filter-btn ${activeFilter===c?"active":""}" data-filter="${esc(c)}">${catIcon(c)} ${esc(c)}</button>`).join("");el.filters.querySelectorAll("button").forEach(b=>b.onclick=()=>{activeFilter=b.dataset.filter;render()})}
function renderProducts(){const visible=activeFilter==="Alle"?products:products.filter(p=>p.kategorie===activeFilter),counts={};entries.forEach(e=>counts[e.produkt]=(counts[e.produkt]||0)+1);el.productArea.innerHTML=visible.map(p=>`<button class="tile ${slug(p.kategorie)}" data-name="${esc(p.produkt)}"><div class="icon">${p.icon}</div><div><div class="name">${esc(p.produkt)}</div><div class="price">${euro(p.preis)}</div></div><div class="count" style="visibility:${counts[p.produkt]?"visible":"hidden"}">${counts[p.produkt]||0}</div></button>`).join("");el.productArea.querySelectorAll(".tile").forEach(btn=>{const p=visible.find(x=>x.produkt===btn.dataset.name);btn.onclick=()=>addEntry(p)})}
function renderCart(){const total=entries.reduce((s,e)=>s+e.preis,0);el.total.textContent=euro(total);el.status.textContent=`${entries.length} Positionen`;const g={};entries.forEach(e=>{const k=e.produkt+"|"+e.preis;g[k]??={name:e.produkt,price:e.preis,count:0};g[k].count++});const rows=Object.values(g);el.cartList.innerHTML=rows.length?rows.map(r=>`<div class="cart-row"><span>${r.count}× ${esc(r.name)}</span><strong>${euro(r.count*r.price)}</strong></div>`).join("")+`<div class="cart-row"><span>Gesamt</span><strong>${euro(total)}</strong></div>`:`<div class="cart-row"><span>Noch keine Positionen</span><strong>${euro(0)}</strong></div>`}
function render(){renderFilters();renderProducts();renderCart();setView(activeView)}
function addEntry(p){if(!p)return;entries.push({...p});if(navigator.vibrate)navigator.vibrate(18);render()}
function setView(v){activeView=v;const list=v==="list";el.productArea.classList.toggle("hidden",list);el.filters.classList.toggle("hidden",list);document.querySelector(".special-actions").classList.toggle("hidden",list);el.cartPanel.hidden=!list;el.cashTab.classList.toggle("active",!list);el.listTab.classList.toggle("active",list)}
el.refreshBtn.onclick=()=>loadProducts(true);el.undoBtn.onclick=()=>{entries.pop();render()};el.resetBtn.onclick=()=>{if(entries.length&&confirm("Aktuelle Rechnung wirklich zurücksetzen?")){entries=[];render()}};el.cashTab.onclick=()=>setView("cash");el.listTab.onclick=()=>setView("list");
if("serviceWorker"in navigator)window.addEventListener("load",()=>navigator.serviceWorker.register("service-worker.js"));loadProducts();
